server:
  port: 18881

spring:
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://daisy.seongwon.org:18880/mydb?useSSL=false&serverTimezone=Asia/Seoul&autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8
    username: seunghee
    password: seunghee


# Logging
LOG_PATH_NAME: /wisoft/logs/backend/dev/apiexample
LOG_FILE_NAME: apiexample
LOG_LEVEL: DEBUG
ROOT_LOG_LEVEL: ERROR

logging:
  file:
    name: ${LOG_PATH_NAME}/${LOG_FILE_NAME}.log
  pattern:
    console: '%d %clr([%-5level]) %replace(%caller{1}){"Caller\+\d  at ",""}%msg%n'
    file: "%d [%-5level]  [%thread]  [%c{25}]  [%method]  %msg%n"
  level:
    root: ${ROOT_LOG_LEVEL}
    io.leeseunghee: ${LOG_LEVEL}
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_PATH_NAME}/${LOG_FILE_NAME}.log.%d{yyyy-MM-dd}_i
      max-file-size: 10MB
      max-history: 60
      total-size-cap: 1GB

#Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health, httptrace, info, metrics, prometheus
